//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Black_friday.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Black_fridayEntities2 : DbContext
    {
        public Black_fridayEntities2()
            : base("name=Black_fridayEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<description> descriptions { get; set; }
        public virtual DbSet<group_products> group_products { get; set; }
        public virtual DbSet<group_sale> group_sale { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<product_to_sale> product_to_sale { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<stores_to_sales> stores_to_sales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user_admin> user_admin { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
