//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Black_friday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stores_to_sales
    {
        public int id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> sales_id { get; set; }
    
        public virtual sale sale { get; set; }
        public virtual store store { get; set; }
    }
}
